name: mlstm4reco
channels:
- pytorch
- maciejkula
- peterjc123
- conda-forge
- intel
- defaults
dependencies:
- ipython
- networkx=1.11
- python=3.6
- pytorch=0.3
- numpy
- pandas
- spotlight=0.1.4
- pip:
  - hyperopt
