name: mlstm4reco
channels:
- pytorch
- maciejkula
- conda-forge
- intel
- defaults
dependencies:
- backcall=0.1.0=py_0
- blas=1.1=openblas
- ca-certificates=2018.4.16=0
- cffi=1.11.5=py36_0
- decorator=4.3.0=py_0
- h5py=2.7.1=py36_2
- hdf5=1.10.1=2
- ipython=6.4.0=py36_0
- ipython_genutils=0.2.0=py_1
- jedi=0.10.2=py36_0
- libffi=3.2.1=3
- ncurses=5.9=10
- networkx=1.11=py36_0
- ninja=1.8.2=1
- numpy=1.14.5=py36_blas_openblash24bf2e0_200
- openblas=0.2.20=8
- openssl=1.0.2o=0
- pandas=0.23.3=py36_0
- pexpect=4.6.0=py36_0
- pickleshare=0.7.4=py36_0
- pip=9.0.3=py36_0
- prompt_toolkit=1.0.15=py36_0
- ptyprocess=0.6.0=py36_0
- pycparser=2.18=py_1
- pygments=2.2.0=py_1
- python=3.6.5=1
- python-dateutil=2.7.3=py_0
- pytz=2018.5=py_0
- readline=7.0=0
- requests=2.13.0=py36_0
- scikit-learn=0.19.2=py36_blas_openblas_200
- scipy=1.1.0=py36_blas_openblas_200
- simplegeneric=0.8.1=py_1
- six=1.11.0=py36_1
- sqlite=3.20.1=2
- tk=8.6.7=0
- traitlets=4.3.2=py36_0
- wcwidth=0.1.7=py_1
- wheel=0.31.1=py36_0
- xz=5.2.3=0
- zlib=1.2.11=0
- certifi=2016.2.28=py36_0
- cudatoolkit=8.0=3
- libgfortran=3.0.0=1
- setuptools=36.4.0=py36_1
- mkl=2018.0.3=intel_1
- openmp=2018.0.3=intel_0
- spotlight=0.1.5=py36_0
- pytorch=0.4.0=py36_cuda8.0.61_cudnn7.1.2_1
- pip:
  - future==0.16.0
  - hyperopt==0.1
  - ipython-genutils==0.2.0
  - mlstm4reco (/home/fwilhelm/Sources/mlstm4reco/src)==0.0.post0.dev4+gbe315c4.dirty
  - nose==1.3.7
  - prompt-toolkit==1.0.15
  - pymongo==3.7.0
  - torch==0.4.0

